-- =============================================================
-- TSURU — ERP para editora
-- Script de criação do banco de dados (PostgreSQL 15+)
-- Convertido a partir do modelo lógico (DER)
-- =============================================================
-- Convenções adotadas:
--   * nomes de tabelas e colunas em snake_case minúsculo
--     (padrão idiomático do Postgres e do que o Prisma espera
--     ao mapear via @@map/@map)
--   * chaves primárias como IDENTITY (o que o Prisma 7 gera
--     por padrão para Int @id @default(autoincrement()) no
--     provider postgresql)
--   * NUMERIC(10,2) para valores monetários
--   * NOT NULL nos campos que o modelo trata como obrigatórios
--   * índices criados manualmente para toda FK, já que o
--     Postgres não indexa FKs automaticamente
-- =============================================================

BEGIN;

-- =============================================================
-- Tabelas sem dependências
-- =============================================================

CREATE TABLE campanha (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150)    NOT NULL,
    descricao   VARCHAR(255),
    data        DATE            NOT NULL,
    status      VARCHAR(30)     NOT NULL
);
COMMENT ON TABLE campanha IS 'Campanhas promocionais que originam devoluções de crédito para os parceiros.';

CREATE TABLE parceiro (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150)  NOT NULL,
    cnpj           CHAR(18)      NOT NULL,
    email          VARCHAR(150),
    telefone       VARCHAR(20),
    ativo          BOOLEAN       NOT NULL DEFAULT TRUE,
    data_cadastro  DATE          NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT uq_parceiro_cnpj UNIQUE (cnpj),
    CONSTRAINT uq_parceiro_telefone UNIQUE (telefone),
    CONSTRAINT ck_parceiro_cnpj_formato
        CHECK (cnpj ~ '^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$')
);
COMMENT ON TABLE parceiro IS 'Parceiros de venda (livrarias/distribuidores) da editora.';

CREATE TABLE produto (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn           VARCHAR(20)   NOT NULL,
    titulo         VARCHAR(255)  NOT NULL,
    autor          VARCHAR(150)  NOT NULL,
    preco          NUMERIC(10,2) NOT NULL,
    data_cadastro  DATE          NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT uq_produto_isbn UNIQUE (isbn)
);
COMMENT ON TABLE produto IS 'Obras (livros) publicadas pela editora.';

CREATE TABLE usuario (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150)  NOT NULL,
    email           VARCHAR(150)  NOT NULL,
    senha           VARCHAR(255)  NOT NULL,
    ativo           BOOLEAN       NOT NULL DEFAULT TRUE,
    perfil          VARCHAR(30)   NOT NULL,
    primeiro_login  BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_usuario_email UNIQUE (email)
);
COMMENT ON TABLE usuario IS 'Usuários do sistema (colaboradores da editora).';

-- =============================================================
-- Tabelas com dependência de 1º nível
-- =============================================================

CREATE TABLE endereco (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logradouro       VARCHAR(150) NOT NULL,
    numero           VARCHAR(10)  NOT NULL,
    bairro           VARCHAR(100) NOT NULL,
    cidade           VARCHAR(100) NOT NULL,
    estado           CHAR(2)      NOT NULL,
    cep              CHAR(8)      NOT NULL,
    fk_parceiro_id   INTEGER      NOT NULL,
    CONSTRAINT fk_endereco_parceiro
        FOREIGN KEY (fk_parceiro_id)
        REFERENCES parceiro (id)
        ON DELETE CASCADE
);
COMMENT ON TABLE endereco IS 'Endereços de entrega vinculados a um parceiro.';

CREATE TABLE ordem_impressao (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(150) NOT NULL,
    data_criacao     DATE         NOT NULL DEFAULT CURRENT_DATE,
    data_aprovacao   DATE,
    total_obras      INTEGER      NOT NULL DEFAULT 0,
    total_unidades   INTEGER      NOT NULL DEFAULT 0,
    status           VARCHAR(30)  NOT NULL,
    fk_usuario_id    INTEGER      NOT NULL,
    CONSTRAINT fk_ordem_impressao_usuario
        FOREIGN KEY (fk_usuario_id)
        REFERENCES usuario (id)
        ON DELETE CASCADE
);
COMMENT ON TABLE ordem_impressao IS 'Ordens de impressão criadas por um usuário, agrupando lotes a serem impressos.';

CREATE TABLE devolucao_credito (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_devolucao    DATE          NOT NULL,
    motivo            VARCHAR(255)  NOT NULL,
    valor_original    NUMERIC(10,2) NOT NULL,
    valor_atual       NUMERIC(10,2) NOT NULL,
    fk_parceiro_id    INTEGER       NOT NULL,
    fk_campanha_id    INTEGER       NOT NULL,
    CONSTRAINT fk_devolucao_credito_parceiro
        FOREIGN KEY (fk_parceiro_id)
        REFERENCES parceiro (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_devolucao_credito_campanha
        FOREIGN KEY (fk_campanha_id)
        REFERENCES campanha (id)
        ON DELETE RESTRICT
);
COMMENT ON TABLE devolucao_credito IS 'Devoluções de produtos convertidas em crédito para o parceiro, associadas a uma campanha.';

-- =============================================================
-- Tabelas com dependência de 2º nível
-- =============================================================

CREATE TABLE lote (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                   VARCHAR(50) NOT NULL,
    quantidade_inicial       INTEGER     NOT NULL,
    quantidade_atual         INTEGER     NOT NULL,
    data_criacao             DATE        NOT NULL DEFAULT CURRENT_DATE,
    status                   VARCHAR(30) NOT NULL,
    fk_ordem_impressao_id    INTEGER     NOT NULL,
    fk_produto_id            INTEGER     NOT NULL,
    CONSTRAINT uq_lote_codigo UNIQUE (codigo),
    CONSTRAINT fk_lote_ordem_impressao
        FOREIGN KEY (fk_ordem_impressao_id)
        REFERENCES ordem_impressao (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_lote_produto
        FOREIGN KEY (fk_produto_id)
        REFERENCES produto (id)
        ON DELETE CASCADE
);
COMMENT ON TABLE lote IS 'Lotes de exemplares impressos de um produto, gerados a partir de uma ordem de impressão.';

CREATE TABLE saida (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_saida       DATE          NOT NULL DEFAULT CURRENT_DATE,
    valor_total      NUMERIC(10,2) NOT NULL,
    valor_final      NUMERIC(10,2) NOT NULL,
    credito_usado    NUMERIC(10,2) NOT NULL DEFAULT 0,
    fk_endereco_id   INTEGER       NOT NULL,
    CONSTRAINT fk_saida_endereco
        FOREIGN KEY (fk_endereco_id)
        REFERENCES endereco (id)
        ON DELETE CASCADE
);
COMMENT ON TABLE saida IS 'Saídas de mercadoria (remessas de venda) enviadas a um endereço de parceiro.';

-- =============================================================
-- Tabelas associativas (relacionamentos N:N com atributos)
-- =============================================================

CREATE TABLE saida_lote (
    fk_saida_id   INTEGER       NOT NULL,
    fk_lote_id    INTEGER       NOT NULL,
    quantidade    INTEGER       NOT NULL,
    subtotal      NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_saida_lote PRIMARY KEY (fk_saida_id, fk_lote_id),
    CONSTRAINT fk_saida_lote_saida
        FOREIGN KEY (fk_saida_id)
        REFERENCES saida (id),
    CONSTRAINT fk_saida_lote_lote
        FOREIGN KEY (fk_lote_id)
        REFERENCES lote (id)
);
COMMENT ON TABLE saida_lote IS 'Associativa entre saída e lote: quais lotes (e em que quantidade) compõem uma saída. Chave primária composta adicionada na conversão — o script original não definia PK para esta tabela.';

CREATE TABLE saida_credito (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_utilizado           NUMERIC(10,2) NOT NULL,
    fk_devolucao_credito_id   INTEGER       NOT NULL,
    fk_saida_id               INTEGER       NOT NULL,
    CONSTRAINT fk_saida_credito_devolucao_credito
        FOREIGN KEY (fk_devolucao_credito_id)
        REFERENCES devolucao_credito (id),
    CONSTRAINT fk_saida_credito_saida
        FOREIGN KEY (fk_saida_id)
        REFERENCES saida (id)
);
COMMENT ON TABLE saida_credito IS 'Associativa entre saída e devolução de crédito: qual crédito (e quanto dele) foi utilizado para abater uma saída.';

CREATE TABLE devolucao_lote (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade                INTEGER NOT NULL,
    fk_lote_id                INTEGER NOT NULL,
    fk_devolucao_credito_id   INTEGER NOT NULL,
    CONSTRAINT fk_devolucao_lote_lote
        FOREIGN KEY (fk_lote_id)
        REFERENCES lote (id),
    CONSTRAINT fk_devolucao_lote_devolucao_credito
        FOREIGN KEY (fk_devolucao_credito_id)
        REFERENCES devolucao_credito (id)
);
COMMENT ON TABLE devolucao_lote IS 'Associativa entre devolução de crédito e lote: quais lotes (e em que quantidade) foram devolvidos.';

-- =============================================================
-- Índices para as colunas de chave estrangeira
-- (o Postgres não cria índice automático em FKs)
-- =============================================================

CREATE INDEX idx_endereco_parceiro            ON endereco (fk_parceiro_id);
CREATE INDEX idx_ordem_impressao_usuario       ON ordem_impressao (fk_usuario_id);
CREATE INDEX idx_devolucao_credito_parceiro    ON devolucao_credito (fk_parceiro_id);
CREATE INDEX idx_devolucao_credito_campanha    ON devolucao_credito (fk_campanha_id);
CREATE INDEX idx_lote_ordem_impressao          ON lote (fk_ordem_impressao_id);
CREATE INDEX idx_lote_produto                  ON lote (fk_produto_id);
CREATE INDEX idx_saida_endereco                ON saida (fk_endereco_id);
CREATE INDEX idx_saida_lote_saida              ON saida_lote (fk_saida_id);
CREATE INDEX idx_saida_lote_lote               ON saida_lote (fk_lote_id);
CREATE INDEX idx_saida_credito_devolucao       ON saida_credito (fk_devolucao_credito_id);
CREATE INDEX idx_saida_credito_saida           ON saida_credito (fk_saida_id);
CREATE INDEX idx_devolucao_lote_lote           ON devolucao_lote (fk_lote_id);
CREATE INDEX idx_devolucao_lote_devolucao      ON devolucao_lote (fk_devolucao_credito_id);

COMMIT;
